---

plugins:
  - jest
  - babel
  - prettier

env:
  node: true
  jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:lodash-fp/recommended'
  - 'prettier'

rules:
  no-console: 0
  prettier/prettier:
    - error
    -
      trailingComma: all
      bracketSpacing: true
